version: '3'

volumes: 
  postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: qr_project_django:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=qr_project
      - POSTGRES_PASSWORD=qr_project
      - POSTGRES_USER=qr_project
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=qr_project
      - POSTGRES_USER=qr_project
      - POSTGRES_PASSWORD=qr_project
