version: '3'

volumes: 
  postgres_data: {}

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    image: "{{ cookiecutter.project_slug }}_django:latest"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_DB={{ cookiecutter.postgres_database }}
      - POSTGRES_PASSWORD={{ cookiecutter.postgres_password }}
      - POSTGRES_USER={{ cookiecutter.postgres_user }}
      - POSTGRES_HOST={{ cookiecutter.postgres_host }}
      - POSTGRES_PORT={{ cookiecutter.postgres_port }}
    depends_on:
      - postgres
  
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # ports:
    #   - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB={{ cookiecutter.postgres_database }}
      - POSTGRES_USER={{ cookiecutter.postgres_user }}
      - POSTGRES_PASSWORD={{ cookiecutter.postgres_password }}
